* Overview

This script if a modification to [alienbob](https://github.com/alienbob)'s Emacs SlackBuild. It allows the
user to create a Slackware package from emacs, elpa, el-get, and org-mode git repositories.  The package versioning is extracted from the Emacs git Master branch. Note that emacs version numbers may
also roll back and forth; however, this does not appear to affect
the use of *upgradepkg*. 

* Installation
Execute the slackbuild.
Note that elpa, el-get and org-mode folders are to be stored in the /usr/share/emacs/lisp/ directory after installation.

* Other Repositories
Emacs and ELPA are official [[https://www.gnu.org/software/][GNU]] software. Note that el-get is not supported by the emacs team.

Emacs repo:
https://git.savannah.gnu.org/git/emacs.git

See https://savannah.gnu.org/git/?group=emacs for more info

[[http://elpa.gnu.org/][ELPA]] repo:
http://git.savannah.gnu.org/cgit/emacs/elpa.git

See https://savannah.gnu.org/git/?group=emacs for more info

el-get can be found at:
https://github.com/dimitri/el-get/

Org-Mode repository can be found at https://orgmode.org/worg/dev/index.html
