* Overview

This script if a modification to AlienBob's SlackBuild. It allows the user to create a Slackware package from the latest git sources of emacs, elpa, el-get, and org-mode.
The package versioning is extract from the Emacs git Master branch. Note that emacs version numbers may also roll back and forth. However, this does not appear to affect
*upgradepkg* command. This script has been used for a few months now to resonably ensure robustness. But ...

USE AT YOUR OWN RISK. 

* Installation

The script does not currently clone each project for you - but it will perform a pull before comiling. Prior to executing **emacs.SlackBuild**,
cd into this proj directory and clone el-get, elpa, emacs-git, and org-mode. 

That is,

$ cd /path/to/Emacs-git-for-Slackware
$ git clone url/for/el-get_git_repo.git>
$ ... etc, etc


If the emacs repo default folder name isn't "emacs-git", change it to that. I intend to fix all this soon; I just haven't gotten around to it. 
However, these values in the script are easily modified.


For reference, my current folder layout is as so:

Emacs-git-Slack
|
|
|------> README.org
|------> el-get  
|------> elpa
|------> emacs-git
|------> emacs.SlackBuild
|------> org-mode

Emacs and ELPA are official [[https://www.gnu.org/software/][GNU]] software.

Emacs repo:
https://git.savannah.gnu.org/git/emacs.git

See https://savannah.gnu.org/git/?group=emacs for more info

[[http://elpa.gnu.org/][ELPA]] repo:
http://git.savannah.gnu.org/cgit/emacs/elpa.git

See https://savannah.gnu.org/git/?group=emacs for more info

el-get can be found at:
https://github.com/dimitri/el-get/

Instructions to clone Org-Mode:
https://orgmode.org/worg/dev/index.html

** Caveats

You'll have to explicitly accept the ELPA copyright agreement. Visit GNU.org for more.

* Upgrading Package

Use the upgradepkg command to update emacs-git. Command use: 
# upgradepkg oldpackge%newpackage.tgz  

For example if the current installation package is named "emacs-26.0.90-1262-x86_64-1_1kito", then the upgrade can be completed by typing the following:
# upgradepkg emacs-26.0.90-1262-x86_64-1_1kito%emacs-26.1-x86_64-1_1kito.txz
Wild Cards also work:
# upgradepkg emacs26.0*%emacs-26.1-x86_64-1_1kito.txz

